version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "Build"
          command: mvn package -Prelease
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}