version: 2.1
jobs:
  build:
    context: Pipeline
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /.*/
    docker:
      - image: maven:3.6.1-jdk-11
    steps:
      - checkout
      - run:
          name: "Configuration"
          command: git clone $GIT_TEMPLATE_URL .scripts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "Build"
          command: mvn $MAVEN_CLI_OPTS package -Prelease
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  release:
    context: Pipeline
    filters:
      tags:
        only: /.*/
      branches:
        ignore: /.*/
    docker:
      - image: maven:3.6.1-jdk-11
    environment:
      MAVEN_CLI_OPTS: "-s .scripts/.m2/settings.xml --batch-mode"
      GIT_TEMPLATE_URL: https://github.com/lorislab/ci-template.git
    steps:
      - checkout
      - run:
          name: "Configuration"
          command: |
            git clone $GIT_TEMPLATE_URL .scripts
            echo "$GPG_KEY_SECRET" | gpg --batch --import --passphrase "$GPG_PASSPHRASE" -
            gpg --list-keys
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "Release"
          command: |
            mvn $MAVEN_CLI_OPTS semver-release:version-release
            mvn $MAVEN_CLI_OPTS clean deploy -Dmaven.test.skip=true -Prelease
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}